USE `chat`;

CREATE TABLE IF NOT EXISTS email_confirmation (
	id INT NOT NULL,
	code CHAR(16) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	username VARCHAR(255) NOT NULL,
	hash CHAR(60) NOT NULL,
	signup_date DATETIME NOT NULL,
	PRIMARY KEY(id)
);