USE `chat`;

CREATE TABLE IF NOT EXISTS user (
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL UNIQUE,
	username VARCHAR(255) NOT NULL,
	hash CHAR(128) NOT NULL,
	salt CHAR(16) NOT NULL,
	signup_date DATETIME NOT NULL,
	PRIMARY KEY(id)
);